import type { NextPage } from 'next'
import Image from 'next/image'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Container, Typography } from '@mui/material'
import NavBar from '../../components/NavBar'
import ContentList from '../../components/ContentList'


const Blog: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <ContentList />
    </div>
  )
}

export default Blog