import React from "react";
import MyEditor from '../components/Editor'
import Head from 'next/head';
import NavBar from "../components/NavBar";
import {Button, TextField} from '@mui/material'
export default function AddPost() {
  return (
    <div>
      <Head>
        <title>Add A Post</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <TextField sx={{marginLeft: '20px', marginTop:'20px', width: '98%'}} id="post-title" label="Title" variant="filled" />
      <TextField sx={{marginLeft: '20px', marginTop:'20px', width: '98%'}} id="post-deck" label="Deck" variant="filled" />
      <MyEditor />
      <Button sx={{marginLeft: '20px'}} color="primary" variant="contained">
          Submit
      </Button>
    </div>
  );
}